name: samurai-env
channels:
  - conda-forge
dependencies:
  - cmake
  - ninja
  - xtensor>0.25
  - highfive>=3.0
  - fmt
  - pugixml
  - cli11<2.5
  - pytest
  - h5py
  # Python bindings dependencies
  - python>=3.8
  - numpy>=1.20
  - pybind11>=2.10
